[package]
name = "benchmark"
version = "0.1.0"
authors = ["mich101mich <mich101mich@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.3"
rayon = "1.0.3"
hierarchical_pathfinding = { path = ".." }
