[package]
name = "benchmark"
version = "0.1.0"
authors = ["mich101mich <mich101mich@gmail.com>"]
edition = "2018"

[dependencies]
rand = { version = "0.8", features = ["std_rng"] }
rayon = "1.5"
hierarchical_pathfinding = { path = ".." }
fnv = "1.0"
