[package]
name = "hierarchical_pathfinding"
version = "0.4.3"
authors = ["mich101mich <mich101mich@gmail.com>"]
edition = "2018"
description = "Quickly approximate Paths on a Grid"
repository = "https://github.com/mich101mich/hierarchical_pathfinding"
readme = "readme.md"
license = "MIT"
keywords = ["pathfinding", "dijkstra", "a-star", "grid"]
categories = ["algorithms"]
exclude = ["/.circleci/*", "/.travis.yml", "/.vscode/*", "/todo.md", "/.gitignore", "/.github/*"]

[dependencies]
fnv = "1.0"
