[package]
name = "hierarchical_pathfinding"
version = "0.1.0"
authors = ["mich101mich <mich101mich@gmail.com>"]
edition = "2018"
description = "A crate to find Paths on a Grid using HPA* (Hierarchical Pathfinding A*) and Hierarchical Dijkstra"
repository = "https://github.com/mich101mich/hierarchical_pathfinding"
readme = "readme.md"
keywords = ["pathfinding", "dijkstra", "a-star", "grid"]
categories = ["algorithms"]

[badges]
circle-ci = { repository = "https://github.com/mich101mich/hierarchical_pathfinding", branch = "master" }

[dependencies]
