[package]
name = "hierarchical_pathfinding"
version = "0.4.3"
authors = ["mich101mich <mich101mich@gmail.com>"]
edition = "2018"
description = "Quickly approximate Paths on a Grid"
repository = "https://github.com/mich101mich/hierarchical_pathfinding"
readme = "readme.md"
license = "MIT"
keywords = ["pathfinding", "dijkstra", "a-star", "grid"]
categories = ["algorithms"]
exclude = [
    "/.vscode/*",
    "/todo.md",
    "/.gitignore",
    "/.github/*",
    "/benchmark/*",
    "/img/*",
]

[dependencies]
hashbrown = "0.11.2"
rayon = { version="1.5.1", optional=true }

[dev-dependencies]
rand = { version="0.8.4", features=["std_rng"] }
profiling = { version="1.0.3", features=["profile-with-optick"] }
criterion = "0.3.4"

[[bench]]
name = "my_benchmark"
harness = false


[features]
default = ["parallel"]
parallel = ["rayon", "hashbrown/rayon"]
