version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.31.0-stretch
    steps:
      - checkout
      - restore_cache:
          key: build-cache
      - run:
          name: Build
          command: cargo build
      - save_cache:
          key: build-cache
          paths:
            - target
  test:
    docker:
      - image: circleci/rust:1.31.0-stretch
    steps:
      - checkout
      - run:
          name: Test
          command: cargo test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master