version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.36.0-buster
    steps:
      - checkout
      - restore_cache:
          key: build-cache
      - run:
          name: Test
          command: cargo test
      - save_cache:
          key: build-cache
          paths:
            - target