version: 2
jobs:
  test:
    docker:
      - image: circleci/rust:1.31.0-stretch
    steps:
      - checkout
      - restore_cache:
          key: test-cache
      - run:
          name: Test
          command: cargo test
      - save_cache:
          key: test-cache
          paths:
            - target